### PR TITLE
high_tier_army_riflemanCCO update

### PR DESCRIPTION
**Pull request by HeroesMaker**
updated riflemanCCO loadout, added CCO to new units and backpacks to missing units
[broma github.txt](https://github.com/Neefay/BromA-Framework-A3-Addon/files/1777430/broma.github.txt)

copy and paste into the already existing .sqf

### CODE REVIEW

**Comment by Neefay** [comment]
That's not how pull requests work bro.

**Comment by HeroesMaker** [comment]
well, sorry i looked at their tutorial but it doesn't explain a lot

**Comment by Parasite42** [comment]
jesus christ heroes, i asked royal for you
Royal:

**Comment by Parasite42** [comment]
go to git
go to the file you you want to change
click on edit
and it will create a fork so you can edit whatever you want and then there's a pull request button

**Comment by HeroesMaker** [comment]
ah alright, i'm doing it now tell me if it work correctly

**Pull request closed without merging**
