### PR TITLE
Spectator: Remove dependency on Headless Client.

### PR DESCRIPTION
**Pull request by Coryf88**

### CODE REVIEW

**Comment by Neefay** [comment]
Are you 100% sure on this one? The HC attachment method was probably the only thing that has really worked so far after lots of different attempts to have the spectator behaving correctly.

**Comment by Coryf88** [comment]
I didn't experience any issues during testing. Do you recall what the issues consisted of with the other attempts?

**Comment by Neefay** [comment]
Cory, I'm gonna close this one for now. I do recall that the main issue was that people on spectator sounded far away from each other, and there was something about enableSimulation that caused that. If people notice problems on the spectator, then we'll try something different.

**Comment by Coryf88** [comment]
Alright, I'll look into the TFAR spectator issue and do further testing.

Removal of the Headless Client dependency was because TvT missions will likely not include the Headless Client plugin, which leads to people who have died to be at the TvT's respawn.

**Comment by badkneegrow** [comment]
I remember this happening on the tvt with bolt actions

**Pull request closed without merging**
